# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MegaDistro
version:      0.02
version_from: lib/MegaDistro.pm
installdirs:  site
requires:
    Archive::Tar:                  0
    CPANPLUS:                      0.0562
    ExtUtils::MakeMaker:           6.17
    File::Spec:                    0.8
    Module::CoreList:              2.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
